### ISSUE TITLE
sidebar very small on android

### ISSUE THREAD

**Issue by hanss314** [HTSTEM/htstem.net#1]
the sidebar is almost invisible on the android default browser

**Comment by Bottersnike** [comment]
Are you able to reproduce the issue on a desktop device using emulation software? (I don't have access to any Android devices)

**Comment by Bottersnike** [comment]
I've fully rewritten the site using bootstrap so this shouldn't happen any more. I'm closing this issue. But if it's still happening, feel free to re-open it.
